INSERT INTO PRODUCT (NAME, PRICE, CATEGORY) VALUES ('Product 1', 10.0, 'Category A');
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY) VALUES ('Product 2', 15.0, 'Category B');
INSERT INTO PRODUCT (NAME, PRICE, CATEGORY) VALUES ('Product 3', 16.5, 'Category C');